<?php
/**
 * @author Ihor Ambrosov <ihor.ambrosov@gmail.com>
 * @license https://opensource.org/licenses/OSL-3.0
 */
?>
<?php if (count($block->getStores()) > 1) : ?>
<?php $id = $block->getIdModifier() ? '-'.$block->getIdModifier() : '' ?>
<div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?= $block->escapeHtmlAttr($id) ?>">
    <strong class="label switcher-label"><span><?= $block->escapeHtml(__('Language')) ?></span></strong>
    <div class="actions dropdown options switcher-options">
        <div class="action toggle switcher-trigger"
             id="switcher-language-trigger<?= $block->escapeHtmlAttr($id) ?>"
             data-mage-init='{"dropdown":{}}'
             data-toggle="dropdown"
             data-trigger-keypress-button="true">
            <strong class="view-<?= $block->escapeHtml($block->getCurrentStoreCode()) ?>">
                <span><?= $block->escapeHtml($block->getStoreName()) ?></span>
            </strong>
        </div>
        <ul class="dropdown switcher-dropdown" data-target="dropdown">
            <?php foreach ($block->getStores() as $store) : ?>
            <?php if ($store->getId() != $block->getCurrentStoreId()) : ?>
            <li class="view-<?= $block->escapeHtml($store->getCode()) ?> switcher-option">
                <a href="#" data-post='<?= $block->getTargetStorePostData($store) ?>'><?= $block->escapeHtml($store->getName()) ?></a>
            </li>
            <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>